// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoardInfo = {
  versionMajor: number;
  versionMinor: number;
  description: string;
};
