// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cpu = {
  /**
   * / Returns load between 0.0 and 100.0
   */
  load: number;
  /**
   * / Returns core frequency in MHz
   */
  frequency: number;
};
