// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * / 2D vector of ints
 */
export type Dim2 = {
  /**
   * / X component
   */
  x: number;
  /**
   * / Y component
   */
  y: number;
};
