// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dim3 } from "./Dim3";
import type { EulerAngles } from "./EulerAngles";
import type { LatLon } from "./LatLon";
import type { Timestamp } from "./Timestamp";

export type Telemetry = {
  coordinate: LatLon | null;
  altitude: number;
  altitudeBarometric: number;
  velocityCourse: number;
  velocityVertical: number;
  gyroscope: Dim3 | null;
  accelerometer: Dim3 | null;
  compass: Dim3 | null;
  gpsCourse: number;
  eulerAxes: EulerAngles | null;
  timestamp: Timestamp | null;
  pressure: number;
  temperature: number;
  satellites: number;
  navigationSource: number;
  fixType: number;
};
