// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * / UUID based on RFC 4122
 */
export type Uuid = {
  /**
   * / The string representation of the UUID
   */
  value: Array<number>;
  /**
   * / The version of the UUID. Can be zero.
   */
  version: number;
};
