// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { Tarball } from "./Tarball";

export type Artifact = { "stdoutText": string } | { "tarball": Tarball } | {
  "file": File;
};
