// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Disk = {
  name: string;
  mountPoint: string;
  total: number;
  used: number;
};
