// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * / Euler angles
 */
export type EulerAngles = {
  /**
   * / Roll component in radians
   */
  roll: number;
  /**
   * / Pitch component in radians
   */
  pitch: number;
  /**
   * / Yaw component in radians
   */
  yaw: number;
};
