// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SockAddr } from "./SockAddr";

export type ExecuteShellRequest = {
  command: string;
  args: Array<string>;
  workingDirectory: number;
  executionPolicy: number;
  artifactType: number;
  forceColor: boolean;
  stdoutPipeAddress: SockAddr | null;
};
