// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { ExecutionResult } from "./ExecutionResult";
import type { Uuid } from "./Uuid";

export type ExecuteShellResponse = {
  taskUuid: Uuid | null;
  pid: number;
  elapsed: Duration | null;
  result: ExecutionResult | null;
};
