// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageMetadata } from "./ImageMetadata";

export type Image = {
  metadata: ImageMetadata | null;
  imageData: Array<number>;
};
