// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { Timestamp } from "./Timestamp";
import type { Uuid } from "./Uuid";

export type ImageMetadata = {
  filename: string;
  uuid: Uuid | null;
  type: number;
  latitude: number;
  longitude: number;
  dx: number;
  dy: number;
  x0: number;
  y0: number;
  lx: number;
  ly: number;
  azimuth: number;
  driftAngle: number;
  divergenceAngle: number;
  velocity: number;
  altitude: number;
  fic: number;
  timeOffset: Duration | null;
  timeDuration: Duration | null;
  timestamp: Timestamp | null;
  sarMode: number;
  validChecksum: boolean;
};
