// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatLon = {
  /**
   * / WGS84 latitude in degrees
   */
  latitude: number;
  /**
   * / WGS84 longitude in degrees
   */
  longitude: number;
};
