// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cpu } from "./Cpu";
import type { Disk } from "./Disk";
import type { MemoryInfo } from "./MemoryInfo";

export type SystemTelemetry = {
  /**
   * / Returns average system cpu load between 0.0 and 100.0
   */
  globalCpuLoad: number;
  cpu: Array<Cpu>;
  disk: Array<Disk>;
  ram: MemoryInfo | null;
};
