// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { Telemetry } from "./Telemetry";

export type TelemetryRecord = {
  telemetry: Array<Telemetry>;
  duration: Duration | null;
  rawData: Array<number>;
};
